MicrosoftLearning/mslearn-azure-developer

instructions/azure-container-services/01-container-image-acr-tasks.md, instructions/azure-container-services/02-run-container-aci.md
=> azure container services exercises

instructions/azure-container-services/02-run-container-aci.md
=> description fix

_layouts/home.html, _layouts/page.html
=> updated layout header

instructions/azure-app-service/01-app-service-deploy-container.md, instructions/azure-app-service/02-app-service-deployment-slots.md, instructions/azure-container-services/01-container-image-acr-tasks.md, instructions/azure-container-services/02-run-container-aci.md, instructions/azure-container-services/03-deploy-to-container-apps.md, instructions/azure-cosmos-db/01-comosdb-create-resources-sdk.md
=> removed exclamation points from notes

instructions/azure-container-services/03-deploy-to-container-apps.md
=> cli formatting test

_config.yml, index.md
=> layout change

_layouts/page.html, index.md
=> Exercise working branch

instructions/azure-storage/01-blob-storage-resources-dotnet.md
=> Fixed piping issue

instructions/azure-storage/01-blob-storage-resources-dotnet.md
=> space still added - question

instructions/azure-storage/01-blob-storage-resources-dotnet.md
=> space fix test

_config.yml
=> trying commonmark

instructions/azure-storage/01-blob-storage-resources-dotnet.md
=> trying 3 spaces

instructions/azure-app-service/01-app-service-deploy-container.md, instructions/azure-app-service/02-app-service-deployment-slots.md, instructions/azure-container-services/01-container-image-acr-tasks.md, instructions/azure-container-services/02-run-container-aci.md, instructions/azure-container-services/03-deploy-to-container-apps.md, instructions/azure-cosmos-db/01-comosdb-create-resources-sdk.md, instructions/azure-functions/01-functions-create-vscode-http.md, instructions/azure-storage/01-blob-storage-resources-dotnet.md
=> updated this exercise takes verbiage

allfiles/labs/dotnet/azure-storage/01-blob-storage-resources-dotnet/Program.cs, instructions/azure-storage/01-blob-storage-resources-dotnet.md
=> instruction and code updates

instructions/azure-storage/01-blob-storage-resources-dotnet.md
=> removed Azure CLI

instructions/azure-container-services/01-container-image-acr-tasks.md, instructions/azure-container-services/02-run-container-aci.md, instructions/azure-container-services/03-deploy-to-container-apps.md, instructions/azure-cosmos-db/01-comosdb-create-resources-sdk.md, instructions/azure-events-messages/media/01-event-grid-events-to-endpoint.md
=> fixed bad useast usage

instructions/azure-events-messages/media/01-event-grid-events-to-endpoint.md
=> bold and spacing fixes

instructions/azure-events-messages/media/01-event-grid-events-to-endpoint.md
=> minor grammar fix

instructions/azure-functions/01-functions-create-vscode-http.md
=> updated instructions

instructions/azure-events-messages/02-event-hubs-send-receive.md
=> removed bash formatting for commands

instructions/azure-events-messages/03-service-bus-send-receive.md, instructions/azure-events-messages/04-queue-storage-send-receive.md
=> queue storage done

instructions/azure-container-services/02-run-container-aci.md
=> updated tasks

instructions/azure-container-services/01-container-image-acr-tasks.md, instructions/azure-container-services/02-run-container-aci.md, instructions/azure-container-services/03-deploy-to-container-apps.md, instructions/azure-events-messages/01-event-grid-events-to-endpoint.md, instructions/azure-events-messages/02-event-hubs-send-receive.md, instructions/azure-events-messages/03-service-bus-send-receive.md, instructions/azure-events-messages/04-queue-storage-send-receive.md
=> small updates

instructions/azure-app-auth/02-graph-user-profile.md
=> Added graph exercise

instructions/azure-api-mgmt/01-api-mgmt-import-api.md, instructions/azure-app-auth/01-msal-interactive-auth.md, instructions/azure-app-auth/02-graph-user-profile.md, instructions/azure-app-service/01-app-service-deploy-container.md, instructions/azure-app-service/02-app-service-deployment-slots.md, instructions/azure-container-services/01-container-image-acr-tasks.md, instructions/azure-container-services/02-run-container-aci.md, instructions/azure-container-services/03-deploy-to-container-apps.md, instructions/azure-cosmos-db/01-comosdb-create-resources-sdk.md, instructions/azure-events-messages/01-event-grid-events-to-endpoint.md, instructions/azure-events-messages/02-event-hubs-send-receive.md, instructions/azure-events-messages/03-service-bus-send-receive.md, instructions/azure-events-messages/04-queue-storage-send-receive.md, instructions/azure-functions/01-functions-create-vscode-http.md, instructions/azure-secure-solutions/01-key-vault-store-retrieve.md, instructions/azure-storage/01-blob-storage-resources-dotnet.md
=> Secure solutions

instructions/azure-secure-solutions/01-key-vault-store-retrieve.md
=> Secure solutions key vault exercise done

instructions/azure-secure-solutions/01-key-vault-store-retrieve.md
=> updated title

index.md
=> before you start update

instructions/azure-app-service/02-app-service-deployment-slots.md
=> fixed formatting issue

instructions/azure-events-messages/01-event-grid-events-to-endpoint.md, instructions/azure-events-messages/02-event-hubs-send-receive.md, instructions/azure-events-messages/03-service-bus-send-receive.md, instructions/azure-events-messages/04-queue-storage-send-receive.md, instructions/azure-secure-solutions/01-key-vault-store-retrieve.md, instructions/azure-secure-solutions/02-app-config-retrieve.md
=> Lots of updates

instructions/azure-events-messages/02-event-hubs-send-receive.md
=> event hubs updates

instructions/azure-cosmos-db/01-comosdb-create-resources-sdk.md
=> Test updates

instructions/azure-api-mgmt/01-api-mgmt-import-api.md, instructions/azure-app-auth/01-msal-interactive-auth.md, instructions/azure-app-service/01-app-service-deploy-container.md, instructions/azure-app-service/02-app-service-deployment-slots.md, instructions/azure-events-messages/01-event-grid-events-to-endpoint.md, instructions/azure-events-messages/04-queue-storage-send-receive.md
=> updating intros and titles

instructions/azure-api-mgmt/01-api-mgmt-import-api.md, instructions/azure-app-auth/01-msal-interactive-auth.md, instructions/azure-app-auth/02-graph-user-profile.md, instructions/azure-app-service/01-app-service-deploy-container.md, instructions/azure-app-service/02-app-service-deployment-slots.md, instructions/azure-container-services/01-container-image-acr-tasks.md, instructions/azure-container-services/02-run-container-aci.md, instructions/azure-container-services/03-deploy-to-container-apps.md, instructions/azure-cosmos-db/01-comosdb-create-resources-sdk.md, instructions/azure-events-messages/01-event-grid-events-to-endpoint.md, instructions/azure-events-messages/02-event-hubs-send-receive.md, instructions/azure-events-messages/03-service-bus-send-receive.md, instructions/azure-events-messages/04-queue-storage-send-receive.md, instructions/azure-secure-solutions/01-key-vault-store-retrieve.md, instructions/azure-secure-solutions/02-app-config-retrieve.md, instructions/azure-storage/01-blob-storage-resources-dotnet.md
=> removed "before you start" section where not needed

instructions/azure-app-auth/01-msal-interactive-auth.md, instructions/azure-app-auth/02-graph-user-profile.md, instructions/azure-cosmos-db/01-comosdb-create-resources-sdk.md, instructions/azure-events-messages/01-event-grid-events-to-endpoint.md, instructions/azure-events-messages/02-event-hubs-send-receive.md, instructions/azure-events-messages/03-service-bus-send-receive.md, instructions/azure-events-messages/04-queue-storage-send-receive.md, instructions/azure-secure-solutions/01-key-vault-store-retrieve.md, instructions/azure-secure-solutions/02-app-config-retrieve.md, instructions/azure-storage/01-blob-storage-resources-dotnet.md
=> removed target framework from console command

instructions/azure-app-auth/02-graph-user-profile.md
=> updated H1 in graph exercise

instructions/azure-secure-solutions/02-app-config-retrieve.md
=> small change to app-config instructions

instructions/azure-app-insights/01-app-insights-auto-instrument.md
=> grammar fix to app insights - 2nd try

instructions/azure-app-auth/01-msal-interactive-auth.md, instructions/azure-app-auth/02-graph-user-profile.md
- Removed leftover steps related to Cloud Shell
=> Update azure-app-auth labs

instructions/azure-functions/01-functions-create-vscode-http.md, instructions/azure-secure-solutions/02-app-config-retrieve.md
Also fixed the issue when creating an AppConfig store.
-
-
-
=> add instructions to for appconfig registration

instructions/azure-secure-solutions/02-app-config-retrieve.md
=> removed unnecessary backslash

instructions/azure-functions/01-functions-create-vscode-http.md
This pull request makes a minor documentation improvement to the Azure Functions setup instructions. The change adds a helpful note to guide users on how to respond to a Visual Studio Code security prompt when opening a new project folder.
* Documentation enhancement:
* Added a note instructing users to click "Yes, I trust the authors" if VS Code displays a trust popup when opening the project folder in `instructions/azure-functions/01-functions-create-vscode-http.md`.
=> LAB: Azure Functions - add note about trusting authors in VS Code for Azure Functions project
